<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <RootNamespace>SvgXaml</RootNamespace>
    <AssemblyName>SvgXaml</AssemblyName>
    <StartupObject>SharpVectors.Converters.MainStartup</StartupObject>
    <ApplicationIcon>Images\SharpVectors.ico</ApplicationIcon>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>WPF0001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="MainApplication.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="MainApplication.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\SharpVectors.ico" />
    <Resource Include="Images\SharpVectors.png" />
    <Resource Include="Images\SmallError.png" />
    <Resource Include="Images\SmallInformation.png" />
    <Resource Include="Images\SmallQuestion.png" />
    <Resource Include="Images\SmallSecurity.png" />
    <Resource Include="Images\SmallSecurityError.png" />
    <Resource Include="Images\SmallSecurityQuestion.png" />
    <Resource Include="Images\SmallSecuritySucess.png" />
    <Resource Include="Images\SmallSecurityWarning.png" />
    <Resource Include="Images\SmallWarning.png" />
    <Resource Include="Images\MinimalWindow.png" />
    <Resource Include="Images\ConsoleConversion.png" />
  </ItemGroup>

</Project>
